version: "3"
services:
  pets:
    container_name: pets
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pets
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
