definitions:
  controller.APIError:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  controller.Pet:
    properties:
      birth_date:
        example: "2013-05-23"
        type: string
      name:
        example: Raaida
        type: string
      owner_id:
        example: 1
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/model.AnimalType'
        example: dog
    type: object
  controller.Vaccine:
    properties:
      animal:
        allOf:
        - $ref: '#/definitions/model.AnimalType'
        example: dog
      description:
        example: vaccine to preventing rage
        type: string
      name:
        example: anti-rabies
        type: string
      scheduled:
        example: 365
        type: integer
    type: object
  model.AnimalType:
    enum:
    - dog
    - cat
    - bird
    - hamster
    type: string
    x-enum-varnames:
    - Dog
    - Cat
    - Bird
    - Hamster
  model.Paging:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  model.Pet:
    properties:
      birth_date:
        type: string
      id:
        type: integer
      name:
        type: string
      owner_id:
        type: integer
      register_date:
        type: string
      type:
        $ref: '#/definitions/model.AnimalType'
    type: object
  model.SearchResponse:
    properties:
      paging:
        $ref: '#/definitions/model.Paging'
      results:
        items:
          $ref: '#/definitions/model.Pet'
        type: array
    type: object
  model.VaccinationPlan:
    properties:
      applied:
        items:
          $ref: '#/definitions/model.Vaccine'
        type: array
      name:
        type: string
      ownerID:
        type: integer
      pending:
        items:
          $ref: '#/definitions/model.Vaccine'
        type: array
      type:
        type: string
    type: object
  model.Vaccine:
    properties:
      animal:
        $ref: '#/definitions/model.AnimalType'
      applied_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      scheduled:
        type: integer
    type: object
info:
  contact: {}
paths:
  /pets/owner/{owner_id}:
    get:
      consumes:
      - application/json
      description: Get a pet list given the owner ID
      parameters:
      - description: owner id to get pets
        in: path
        name: owner_id
        required: true
        type: integer
      - description: offset of the results
        in: query
        name: offset
        type: integer
      - description: 'limit of the results '
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SearchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get pets of owner
      tags:
      - Pet
  /pets/pet:
    post:
      consumes:
      - application/json
      description: Create a pet for a given user
      parameters:
      - description: pet info
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/controller.Pet'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Creates a Pet
      tags:
      - Pet
  /pets/pet/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a pet given a pet ID
      parameters:
      - description: id of the pet
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Delete a Pet
      tags:
      - Pet
    get:
      consumes:
      - application/json
      description: Get pet info given a pet ID
      parameters:
      - description: id of the pet
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get a Pet
      tags:
      - Pet
    put:
      consumes:
      - application/json
      description: Edit pet info given a pet ID and pet info needed to update
      parameters:
      - description: id of the pet
        in: path
        name: id
        required: true
        type: integer
      - description: pet info
        in: body
        name: pet
        required: true
        schema:
          $ref: '#/definitions/controller.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Pet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Edit a Pet
      tags:
      - Pet
  /vaccines/apply/{vaccine_id}/to/{pet_id}:
    post:
      consumes:
      - application/json
      description: Apply vaccine to a given pet
      parameters:
      - description: vaccine id to apply on pet
        in: path
        name: vaccine_id
        required: true
        type: integer
      - description: pet id of the target pet
        in: path
        name: pet_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Apply vaccine
      tags:
      - Vaccine
  /vaccines/plan/{pet_id}:
    get:
      consumes:
      - application/json
      description: Get the vaccination plan of given pet_id
      parameters:
      - description: pet id to get vaccines
        in: path
        name: pet_id
        required: true
        type: integer
      - description: desired formant for the output
        enum:
        - applied
        - pending
        in: query
        name: output
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.VaccinationPlan'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get vaccination plan
      tags:
      - Vaccine
  /vaccines/vaccine:
    post:
      consumes:
      - application/json
      description: Create a vaccine
      parameters:
      - description: vaccine info
        in: body
        name: vaccine
        required: true
        schema:
          $ref: '#/definitions/controller.Vaccine'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Vaccine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Creates a Vaccine
      tags:
      - Vaccine
  /vaccines/vaccine/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Vaccine given a pet ID
      parameters:
      - description: id of the vaccine
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Delete a Vaccine
      tags:
      - Vaccine
    get:
      consumes:
      - application/json
      description: Get vaccine info
      parameters:
      - description: id of the vaccine
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Vaccine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get a Vaccine
      tags:
      - Vaccine
    put:
      consumes:
      - application/json
      description: Edit vaccine info given a pet ID and vaccine info needed to update
      parameters:
      - description: id of the vaccine
        in: path
        name: id
        required: true
        type: integer
      - description: vaccine info
        in: body
        name: vaccine
        required: true
        schema:
          $ref: '#/definitions/controller.Vaccine'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Vaccine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Edit a Vaccine
      tags:
      - Vaccine
swagger: "2.0"
